name: "Pipeline - Manual e Agendada"

# ----------------------------------------------------
# GATILHOS / TRIGGERS
# ----------------------------------------------------
on:
  # Gatilho 1: Dispara sempre que houver um envio de código (push)
  push:
    branches:
      - main # Altere para 'master' se a sua branch principal tiver esse nome

  # Gatilho 2: Permite que você clique no botão "Run workflow" no site do GitHub
  workflow_dispatch:

  # Gatilho 3: Faz a pipeline rodar sozinha de tempos em tempos (Schedule)
  schedule:
    - cron: '*/15 * * * *'

# ----------------------------------------------------
# TAREFAS / JOBS
# ----------------------------------------------------
jobs:
  testes-mocha:
    name: Rodar Testes Mocha
    runs-on: ubuntu-latest # Roda na nuvem do GitHub

    steps:
      # 1. Faz o clone do seu projeto para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajuste para a versão do seu projeto se necessário

      # 3. Instala as dependências do seu projeto (npm ou yarn)
      - name: Instalar dependências
        run: npm install

      # PASSO ALTERADO: Dá permissão de execução explicitamente para os binários locais e roda o teste
      - name: Executar testes com Mocha
        run: |
          chmod -R +x ./node_modules/.bin/
          npm test

        # NOVO PASSO: Salva o relatório de execução no GitHub Actions
      - name: Armazenar Relatório de Testes
        uses: actions/upload-artifact@v4
        if: always() # GARANTE que o relatório vai subir mesmo se o teste falhar!
        with:
          name: relatorio-execucao-mocha # Nome do arquivo ZIP que você vai baixar
          path: mochawesome-report/      # Pasta onde o Mochawesome salvou o HTML
          retention-days: 20             # O GitHub vai guardar esse arquivo por 20 dias


          # Um NOVO RELATÓRIO NATIVO: Cria um sumário com gráficos no GitHub
      - name: Publicar Relatório de Testes Nativo
        uses: dorny/test-reporter@v1
        if: always() # Roda mesmo se os testes falharem
        with:
          name: Relatório de Testes Mocha # Nome que vai aparecer na aba de Jobs
          path: test-results.xml          # Caminho do arquivo XML gerado
          reporter: java-junit            # Formato do arquivo (JUnit)